# Game Settings
max_players: 4

# World
start_life: 100
extra_health: 25
null_state: 0
initial_worms_turn: 0
turn_time: 60
wind_min: 0.2
wind_max: 10

# Physics Constants
worm_speed: 2
worm_jump_speed: 6
worm_jump_hor_speed: 3
worm_backflip_speed: 8
worm_backflip_hor_speed: 1

explosion_power: 25
explosion_fragment_power: 5
projectile_potency: 8

# Weapons
bazooka_damage: 50
bazooka_radius: 2
bazooka_misile_restitution: 0
bazooka_misile_density: 0.5

mortar_damage: 50
mortar_radius: 2
mortar_fragments: 6
mortar_misile_restitution: 0
mortar_misile_density: 0.5
mortar_max_ammo: 10

green_grenade_damage: 30
green_grenade_radius: 2
green_grenade_restitution: 0.3
green_grenade_density: 1

red_grenade_damage: 30
red_grenade_radius: 2
red_grenade_fragments: 6
red_grenade_max_ammo: 10
red_grenade_restitution: 0.3
red_grenade_density: 1

banana_damage: 70
banana_radius: 2
banana_restitution: 1
banana_density: 0.8
banana_max_ammo: 5

holy_grenade_damage: 110
holy_grenade_radius: 8
holy_grenade_restitution: 0.3
holy_grenade_density: 1
holy_grenade_max_ammo: 2

dynamite_damage: 50
dynamite_radius: 4
dynamite_max_ammo: 5
dynamite_restitution: 0.3
dynamite_density: 1

baseball_bat_damage: 10
baseball_bat_power: 20

airstrike_damage: 40
airstrike_radius: 2
airstrike_max_ammo: 2

fragment_damage: 10
fragment_radius: 2

#Provision Boxes
health_box_life: 25

trap_box_damage: 30
trap_box_power: 40
trap_box_radius: 2

ammo_box_ammo: 1