# Game Settings
max_players: 4

# Platforms
plat_small: 3
plat_big: 6
plat_height: 0.8
plat_friction: 0.1

# Worms
worm_width: 1.5
worm_height: 1.5
worm_friction: 1

# World
start_life: 100
null_state: 0
initial_worms_turn: 0
turn_time: 10

# Physics Constants
worm_speed: 2
worm_jump_speed: 4
worm_jump_hor_speed: 3
worm_backflip_speed: 6
worm_backflip_hor_speed: 1

explosion_power: 2

# Weapons
bazooka_damage: 50
bazooka_radius: 2
bazooka_type: 1
bazooka_misile_restitution: 0
bazooka_misile_density: 0.5

mortar_damage: 50
mortar_radius: 2
mortar_type: 2
mortar_fragments: 6

green_granade_damage: 30
green_granade_radius: 2
green_granade_type: 3

red_granade_damage: 30
red_granade_radius: 2
red_granade_type: 4
red_granade_fragments: 6

banana_damage: 30
banana_radius: 2
banana_type: 6

holy_granade_damage: 50
holy_granade_radius: 2
holy_granade_type: 5

airstrike_damage: 30
airstrike_radius: 2
airstrike_type: 7

dynamite_damage: 50
dynamite_radius: 2
dynamite_type: 8

baseball_bat_damage: 30
baseball_bat_radius: 2
baseball_bat_type: 9

